### ISSUE TITLE
Pinnacle suggestions - ServerSideMap, Auto pin

### ISSUE THREAD

**Issue by SipeP** [redseiko/ComfyMods#14]
Hello,
Would be nice if this mod was compatible with:
https://valheim.thunderstore.io/package/Mydayyy/ServerSideMap/
Or to implement similar functionality for sharing map & pins with other players.

Also I would appreciate some kind of automatic Pin Creation when interacting with stuff - crypts, dungeons, ores, berries etc...
Similar to: https://www.nexusmods.com/valheim/mods/182?tab=description
Track boats and carts on the map would be useful too.

**Comment by redseiko** [comment]
I won't personally implement those features since their time and effort requirements are significant and beyond the scope of this mod (and already exist in other mods/features).

For FR 1: can be done using the vanilla Cartography table.
For FR 2: you've linked to a mod that already create those pins for you.

Pinnacle's scope is to UI and touches the UI portions of pin creation/finding/filtering.
