### ISSUE TITLE
[Suggestions] PotteryBarn - Placing Items in other category via config + HammerTime compatibility

### ISSUE THREAD

**Issue by Hemalurgist** [redseiko/ComfyMods#20]
Hello! I love this mod and think it would be great to have a config option that lets you add them to another category instead of making their own.

Re HammerTime - this mod is currently testing the ability to consolate/rename piece mod categories (an update that may be released in the near future). I've been helping MSchmoecker test 15+ piece mods and all of them are picked up save for PotteryBarn.  Per the author, _'the pieces in PotteryBarn are not added to the hammer when HammerTime looks for them, so they don't get picked up.'_  Would it be possible to change when the pieces get added to so they're seen by HammerTime?

Thanks for reading!

**Comment by redseiko** [comment]
You're going to need to provide more details for the mod you want compatibility with. Link to a public open repo would help to see what's it doing.

As for config option, the mod isn't meant to be flexible and customizable for use outside of Comfy so you'll need to provide a very good reason why the effort would be required from this end.

Additionally, the pieces are added to the Hammer table at some point by the fact they are accessible with the hammer. There are multiple ways for your mod author to pick up on them such as even patching the PotteryBarn.GetOrAddPieceComponent static method which takes a PieceTable as an argument.

If no further comments I will close this issue in a few days.

**Comment by MSchmoecker** [comment]
To provide you the code for HammerTime: https://github.com/MSchmoecker/HammerTime

I've looked into this a bit more and the issue seems to be that PotteryBarn is adding the pieces at one of the last opportunities and then waits another frame which is exactly one frame too long.
If I compile the mod without the additional frame (https://github.com/redseiko/ComfyMods/blob/main/PotteryBarn/PotteryBarn.cs#L56) it's working as expected.
I also don't see why it's done in a coroutine in the first place, maybe it would be good for you to convert it a normal method as this also simplifies your code.

If you don't want to add compatibility in your mod, I will delay the HammerTime patch even further. This is not the preferred solution as this will interfere with other mods like WackysDB so I would be glad if you can change it in your mods.

For the config option I agree, there is no big reason for you too do, although it would be simple to do.

**Comment by redseiko** [comment]
Removed yield return null in `v1.4.0`.

Protip: next time you can't see why something is done a certain way, ask why. Your suggestions were not asked for nor are welcome here.
