### ISSUE TITLE
Error with the Pottery Barn armor stands : chest armore not fully shown

### ISSUE THREAD

**Issue by Re-nard** [redseiko/ComfyMods#34]
Hi redseiko !

Thanks for Pottery Barn it's been a lovely mod 😄 .
I found out that both female and male armor stands are working properly but for the chest armor : only the arms are displayed.
I made a screen shot as I thought you'd be interested in knowing that. I loaded only your mod to be sure it is not induced by a mod combo.
Here it is, hit me up if you need more details :
![image](https://user-images.githubusercontent.com/123848483/217400130-e5fd250a-1efa-440a-ae31-dda702442cd4.png)

Have a nice day !

Edit : did not tried with other armors, may try later.

**Comment by redseiko** [comment]
So the ArmorStands are vanilla from IronGate so it'd have to be fixed by them (although since these items are not official in game I'm not sure they would).

I've narrowed it down to the material in the ArmorStand/Visual/body sub-GameObject, specifically the first material (PlayerMaterialArmorStand) used for the SkinnedMeshRenderer.

Left is when I apply the Player version (PlayerMaterial) to the ArmorStand versus the default material in the right.

![image](https://user-images.githubusercontent.com/3688670/217471804-1a6b9848-57d8-49c8-8577-b9227c9a6326.png)

**Comment by Re-nard** [comment]
Ooooh I did not realize these stands are in the vanilla game, I thought you created them ! But ok, makes sense since the Pottery Barn mod allows to build prefabs from the game. Sorry for having opened an issue for that 🤣 .
And thanks for your answer ! Have a nice day !

**Comment by redseiko** [comment]
No problem.
