### ISSUE TITLE
[Feature Request] Sears Catalogue AUGA Compatibility

### ISSUE THREAD

**Issue by Crawmak** [redseiko/ComfyMods#63]
Sorry if this is the wrong place to request this. But, basically the title.
AUGA's Build Hud needs to be disabled for this mod to work, which makes the hud difference a little jarring. If possible, an AUGA patch would be greatly appreciated. This seems to be the only mod left that increases build hud size that's still compatible, so I'd hate to have to choose between this and having a halfway decent UI !

**Comment by redseiko** [comment]
Auga can patch SearsCatalog with their own changes needed, or just pull in the code themselves.

**Comment by Vapok** [comment]
Thanks for the link Red.  @Crawmak There's no intention of changing the build menu for Auga at this point as we are in the process of reworking Auga for a 2.0 release. The functionality provided to disable the Build Menu is the stop gap I made available in order to allow folks to use the amazing Sears Catalogue without disabling Auga completely.
